---
engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  golint:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths: []
